### ISSUE TITLE
Generate random version number

### ISSUE THREAD

**Issue by stephane-r** [jansanchez/gulp-css-url-versioner#2]
Hi mate,

Your plugin is fine :) But, do you know if i can generate random version number ?

I've add function to 'version' var, but don't work.

If you have any idea, thank youuuu :)

**Comment by jansanchez** [comment]
Hi friend,

How are you?.

To add a random version would be like:

``` javascript
var gulp = require('gulp'),
    cssVersioner = require('gulp-css-url-versioner'),
    randomVersion = Math.floor(Math.random() * 1000) + 1;

gulp.task('styles', function () {
    return gulp.src('src/css/withoutVersion.css')
    .pipe(cssVersioner({version: randomVersion}))
    .pipe(gulp.dest('dist/css/withVersion.css'));
});
```

I'm sorry for make this option so hard to use :(, maybe later I'll fix that. If you have a doubt, you don't doubt for tell me.

Thanks for your interest.

**Comment by stephane-r** [comment]
Thank you @jansanchez ! Work very nice :)
